#!/usr/bin/env bash

# Install script for restic backup script and associated files
#
# Files: env, excludes, password, restic-backup, restic-backup,service,
# restic-backup.timer

config_dir="$HOME/.config/restic"
bin_dir="$HOME/.local/bin"
systemd_dir="$HOME/.config/systemd/user"
systemd_unit="restic-backup.timer"

for d in "$config_dir" "$bin_dir" "$systemd_dir"; do
	mkdir --parents "$d"
done
cp --update=none env excludes password "$config_dir"
cp --update=none restic-backup "$bin_dir"
cp --update=none restic-backup.{service,timer} "$systemd_dir"

systemctl --user daemon-reload
if systemctl --user is-enabled $systemd_unit &> /dev/null; then
	systemctl --user restart $systemd_unit
else
	systemctl --user --now enable $systemd_unit
fi
