#!/usr/bin/env bash

# Functions
notify () {
	# Desktop pop-up notifications
	notify-send 'Restic encountered an error'
}

run_backup () {
	# Perform backup with configured options
	restic backup "$backup_source" "${backup_options[@]}"
}

run_forget () {
	# Perform forget with configured options
	restic forget "${forget_options[@]}"
}

run_check () {
	# Process consistency checks
}

check_lock () {
	# Check for stale locks and remove
	local exit_code="$1"
	local exit_description="$2"
	local operation_function="$3"
	
	if [[ "$exit_code" -eq 11 ]] then
		echo "$exit_description Attempting to unlock."
		if restic unlock; then
			echo "Unlock successful. Retrying $operation_function."
			"$operation_function"
			return $?
		else
			echo "Unlock failed. Aborting $operation_function." >&2
			return 1
		fi
	fi

	return "$exit_code"
}

# General configuration
config_dir="$HOME/.config/restic"
env_file="$config_dir/env"
backup_source="$HOME"
exclude_file="$config_dir/excludes"
backup_options=(
	--one-file-system
	--exclude-file="$exclude_file"
	--exclude-caches
)
forget_options=(
	--keep-hourly=24
	--keep-daily=14
	--keep-weekly=8
	--keep-monthly=3
	--prune
)
exit_codes=(
	[0]='Command was successful.'
	[1]='Command failed, see command help for more details.'
	[2]='Go runtime error.'
	[3]='Backup command could not read some source data.'
	[10]='Repository does not exist.'
	[11]='Failed to lock repository.'
	[12]='Wrong password.'
	[130]='Restic was interrupted using SIGINT or SIGSTOP.'
)
recipient='nicholaswilson97@gmail.com'

# Pre-run checks
#
# Source env file or exit with error
if ! source "$env_file"; then
	echo "Unable to source $env_file" >&2
	notify
	exit 1
fi

# Detect VPN and set repo host accordingly
repo_host="${RESTIC_REPOSITORY#*@}"
repo_host="${repo_host%%:*}"

# Ping check repo host and exit if unreachable
end=$(( SECONDS + 300 ))
while true; do
	if ping -c 1 -W 2 "$repo_host" &> /dev/null; then
		break
	elif (( SECONDS >= end )); then
		echo "Unable to reach $repo_host" >&2
		exit 1
	fi
	echo 'Waiting for network'
	sleep 1
done

# Perform backup and store exit code
run_backup
backup_exit_code=$?

check_lock "$backup_exit_code" \
	"${exit_codes[$backup_exit_code]:-Unknown exit code}" run_backup
backup_exit_code=$?

echo "Restic backup exited with code $backup_exit_code:" \
	"${exit_codes[$backup_exit_code]:-Unknown exit code}"

# Forget (only if backup is successful)
if (( backup_exit_code == 0 )); then
	run_forget
	forget_exit_code=$?

	check_lock "$forget_exit_code" \
		"${exit_codes[$forget_exit_code]:-Unknown exit code}" run_forget
	forget_exit_code=$?

	echo "Restic forget exited with code $forget_exit_code:" \
		"${exit_codes[$forget_exit_code]:-Unknown exit code}"
else
	forget_exit_code=1
	forget_exit_description='Skipped because backup failed.'
fi

if (( backup_exit_code == 0 && forget_exit_code == 0 )); then
	{
		echo "To: $recipient"
		echo "Subject: $HOSTNAME Restic has completed successfully"
		echo
		echo "Restic exited with code 0: Command was successful."
	} | msmtp -t -a default
	exit 0
else
	{
		echo "To: $recipient"
		echo "Subject: $HOSTNAME Restic encountered an error"
		echo
		echo "Restic backup exit code: $backup_exit_code: " \
			"${exit_codes[$backup_exit_code]:-Unknown exit code} " \
		    	"Restic forget exit code: $forget_exit_code: " \
			"${exit_codes[$forget_exit_code]:-Unknown exit code}"
	} | msmtp  -t -a default
	notify
	exit 1
fi
